// <auto-generated />
using System;
using EntradasHuacales.api9.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntradasHuacales.api9.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251014005345_NuevaMigracion")]
    partial class NuevaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EntradasHuacales.api9.Models.EntradaDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TipoHuacalTipoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("TipoHuacalTipoId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("EntradasHuacales.api9.Models.EntradaHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEntrada");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("EntradasHuacales.api9.Models.TipoHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");
                });

            modelBuilder.Entity("EntradasHuacales.api9.Models.EntradaDetalle", b =>
                {
                    b.HasOne("EntradasHuacales.api9.Models.EntradaHuacales", "EntradaHuacales")
                        .WithMany("Detalle")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntradasHuacales.api9.Models.TipoHuacales", "TipoHuacal")
                        .WithMany()
                        .HasForeignKey("TipoHuacalTipoId");

                    b.Navigation("EntradaHuacales");

                    b.Navigation("TipoHuacal");
                });

            modelBuilder.Entity("EntradasHuacales.api9.Models.EntradaHuacales", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
